### ISSUE TITLE
NGRX/DB WTF?

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/ngrx.github.io#3]
Hi. :)

I'm just wondering how you were able to figure out how to use ngrx/db and why there is no documentation anywhere. Thanks!

**Comment by MikeRyanDev** [comment]
No one is actively maintaining the project. Latest is published to npm, there are unit tests around it, and the source code is pretty small if you need it. Otherwise, as the README says:

> Don't use me yet.

**Comment by JimLynchCodes** [comment]
@MikeRyan52  I don't understand. Is ngrx/db finished? Is there some bug in it that it's not ready to be used? Why not just update the README with some usage instructions? 

Is it just a wrapper around the normal indexDB api? Is there any difference between this and using regular indexedDB in an @Effect?

Are the indexedDB operations in their own web worker?

Having this joke README is completely unprofessional and a huge black eye for Ngrx as a whole. Let's update it. :)

**Comment by MikeRyanDev** [comment]
> Having this joke README is completely unprofessional

No one is getting paid to work on ngrx
