### ISSUE TITLE
@ngrx/effects/index"' has no exported member 'runEffects'

### ISSUE THREAD

**Issue by mxchange** [ngrx/ngrx.github.io#5]
This example:
https://github.com/ngrx/ngrx.github.io/tree/master/effects#effects
`import { runEffects } from '@ngrx/effects';`

Refers to a `runEffects` method, but this does not exist.

**Comment by abdulhaq-e** [comment]
The official example for `ngrx` tools is here: https://github.com/ngrx/example-app/

I believe the content of your link refers to the old version of `ngrx/effects`.

**Comment by brandonroberts** [comment]
Yes, the documentation in this repo is outdated. We'll update the links to go to the repo documentation
