### ISSUE TITLE
Selectors are empty

### ISSUE THREAD

**Issue by JimLynchCodes** [ngrx/ngrx.github.io#6]
The whole folder for selectors is filled with empty files. Can share more info and examples on selectors? :)

**Comment by JimLynchCodes** [comment]
Excuse me, but why was this issue closed??

**Comment by btroncone** [comment]
Hello,

When I was working on these docs I put placeholder files in for sections I planned to complete. I was using this as an outline. Unfortunately I have not been able to get back to them in a while but as time allows I will fill in these files. Thank you for your interest!  👍

**Comment by JimLynchCodes** [comment]
ok. I want to be notified when you do add the files though. 

Can you please reopen this issue and close it once it is completed...? 
`>_<`
